Management/UI/Old/TaskSchedulerManager.Web/Controllers/OrganizationSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using TaskSchedulerManager.Web.Models.OrganizationSettingsViewModels;
using TaskSchedulerManager.Services.Interfaces;
using TaskSchedulerManager.Domain;
using NToastNotify;
using Microsoft.Extensions.Options;
using TaskSchedulerManager.Middleware;

namespace TaskSchedulerManager.Web.Controllers
{
    [Authorize(Roles = "SuperUser")]
    public class OrganizationSettingsController : Controller
    {
        private IMainService _mainService;
        private CreateOrganizationSettingsViewModel _vm;
        private IToastNotification _toastNotification;
        private IOptions<TenantMiddlewareOptions> _options;

        public OrganizationSettingsController(IMainService mainService, IToastNotification toastNotification, IOptions<TenantMiddlewareOptions> options)
        {
            _mainService = mainService;

            _vm = new CreateOrganizationSettingsViewModel();

            _toastNotification = toastNotification;

            _options = options;
        }
        public IActionResult Index()
        {

            return View();
        }



        public IActionResult Display(long id)
        {
            var dto = _mainService.GetOrganizationById(id);

            _vm.AccessKey = dto.AccessKey;
            _vm.Disabled = dto.Disabled;
            _vm.Notes = dto.Notes;
            _vm.TenantAlias = dto.TenantAlias;
            _vm.TenantDatabase = dto.TenantDatabase;
            _vm.TenantDomain = dto.TenantDomain;
            _vm.TenantId = dto.TenantId;
            _vm.TenantName = dto.TenantName;

            return View(_vm);
        }




        public IActionResult New()
        {
            return View(_vm);
        }

        [HttpPost]
        public IActionResult New(CreateOrganizationSettingsViewModel vm)
        {
            try
            {
                OrganizationSettingsDTO dto = new OrganizationSettingsDTO()
                {
                    AccessKey = vm.AccessKey,
                    Disabled = vm.Disabled,
                    Notes = vm.Notes,
                    TenantAlias = vm.TenantAlias,
                    TenantDatabase = vm.TenantDatabase,
                    TenantDomain = vm.TenantDomain,
                    TenantId = vm.TenantId,
                    TenantName = vm.TenantName
                };

                _mainService.AddOrganization(dto);



                _toastNotification.AddToastMessage("New Organization", $"A new organization {dto.TenantAlias} was created with success!", ToastEnums.ToastType.Success, new ToastOption()
                {
                    PositionClass = NToastNotify.Constants.ToastPositions.TopCenter,
                });

                return RedirectToAction("Display", new { id = dto.TenantId });
            }
            catch (Exception ex)
            {
                _toastNotification.AddToastMessage("Error", "Couldn't create organization this time...", ToastEnums.ToastType.Error, new ToastOption()
                {
                    PositionClass = NToastNotify.Constants.ToastPositions.TopCenter
                });

                return RedirectToAction("New");
            }


        }




        public IActionResult Edit(int id)
        {
            var dto = _mainService.GetOrganizationById(id);

            var vm = new CreateOrganizationSettingsViewModel()
            {
                AccessKey = dto.AccessKey,
                Disabled = dto.Disabled,
                Notes = dto.Notes,
                TenantAlias = dto.TenantAlias,
                TenantDatabase = dto.TenantDatabase,
                TenantDomain = dto.TenantDomain,
                TenantId = dto.TenantId,
                TenantName = dto.TenantName
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit(CreateOrganizationSettingsViewModel org)
        {

            try
            {
                var dto = new OrganizationSettingsDTO()
                {
                    AccessKey = org.AccessKey,
                    Disabled = org.Disabled,
                    Notes = org.Notes,
                    TenantAlias = org.TenantAlias,
                    TenantDatabase = org.TenantDatabase,
                    TenantDomain = org.TenantDomain,
                    TenantId = org.TenantId,
                    TenantName = org.TenantName
                };

                _mainService.UpdateOrganization(dto);

                _toastNotification.AddToastMessage("Update", $"Organization {org.TenantAlias} updated with success!", ToastEnums.ToastType.Success, new ToastOption()
                {
                    PositionClass = NToastNotify.Constants.ToastPositions.TopCenter
                });

                return RedirectToAction("Display", new { id = org.TenantId });
            }
            catch (Exception ex)
            {
                _toastNotification.AddToastMessage("Error", "Couldn't update this time... Try again later.", ToastEnums.ToastType.Error, new ToastOption()
                {
                    PositionClass = NToastNotify.Constants.ToastPositions.TopCenter
                });

                return RedirectToAction("Edit", new { id = org.TenantId });
            }
        }



        public IActionResult Delete(long id)
        {
            try
            {
                _mainService.DeleteOrganization(id);

                _toastNotification.AddToastMessage("Delete", "Organization deleted with success!!", ToastEnums.ToastType.Success, new ToastOption()
                {
                    PositionClass = NToastNotify.Constants.ToastPositions.TopCenter
                });

            }
            catch (Exception ex)
            {
                _toastNotification.AddToastMessage("Error", "Couldn't delete this time... Try again later.", ToastEnums.ToastType.Error, new ToastOption()
                {
                    PositionClass = NToastNotify.Constants.ToastPositions.TopCenter
                });
            }

            return RedirectToAction("List");
        }




        public IActionResult List()
        {
            var allOrganizations = _mainService.GetTenantsList();

            List<CreateOrganizationSettingsViewModel> list = new List<CreateOrganizationSettingsViewModel>();


            if (!_options.Value.GrantSuperUserAccess)
            {
                allOrganizations = allOrganizations.Where(org => org.TenantName == _options.Value.TenantName);
            }
            

            foreach (var dto in allOrganizations)
            {
                list.Add(new CreateOrganizationSettingsViewModel()
                {
                    AccessKey = dto.AccessKey,
                    Disabled = dto.Disabled,
                    Notes = dto.Notes,
                    TenantAlias = dto.TenantAlias,
                    TenantDatabase = dto.TenantDatabase,
                    TenantDomain = dto.TenantDomain,
                    TenantId = dto.TenantId,
                    TenantName = dto.TenantName
                });
            }

            return View(list);
        }
    }
}

Management/UI/Old/TaskSchedulerManager.Web/Views/OrganizationSettings/Display.cshtml
@model TaskSchedulerManager.Web.Models.OrganizationSettingsViewModels.CreateOrganizationSettingsViewModel
@{
    ViewData["Title"] = "New";
}





<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="blue">
            <h4 class="title">Organization</h4>
            <p class="category">Add details for the new organization</p>
        </div>
        <div class="card-content">
            <form asp-controller="OrganizationSettings" asp-action="Edit" method="get">
                <div class="row">
                    <div class="col-md-1">
                        <div class="form-group label-floating">
                            <label class="control-label">ID</label>
                            <input typeof="text" class="form-control" asp-for="@Model.TenantId" readonly>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group label-floating">

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="optionsCheckboxes" asp-for="Disabled" readonly>
                                    Disabled
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Company name</label>
                            <input type="text" class="form-control" asp-for="TenantName" readonly>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Alias</label>
                            <input type="text" class="form-control" asp-for="TenantAlias" readonly>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Access Key</label>
                            <input type="text" class="form-control" asp-for="AccessKey" readonly>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Domain Name</label>
                            <input type="text" class="form-control" asp-for="TenantDomain" readonly>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group label-floating">
                            <label class="control-label">Database Name</label>
                            <input type="text" class="form-control" asp-for="TenantDatabase" readonly>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Notes</label>
                            <div class="form-group label-floating">
                                <label class="control-label"> Enter additional information here...</label>
                                <textarea class="form-control" rows="5" asp-for="Notes" readonly></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <a asp-controller="OrganizationSettings" asp-action="List" class="btn btn-primary pull-right">Return</a>
                <a asp-controller="OrganizationSettings" asp-action="Edit" asp-route-id="@Model.TenantId" class="btn btn-primary pull-right">Edit</a>
                <div class="clearfix"></div>
            </form>

        </div>
    </div>
</div>

Management/UI/Old/TaskSchedulerManager.Web/Views/OrganizationSettings/Edit.cshtml
@model TaskSchedulerManager.Web.Models.OrganizationSettingsViewModels.CreateOrganizationSettingsViewModel
@{
    ViewData["Title"] = "Edit";
}





<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="blue">
            <h4 class="title">Organization</h4>
            <p class="category">Edit details for the organization</p>
        </div>
        <div class="card-content">
            <form asp-controller="OrganizationSettings" asp-action="Edit" method="post">
                <div class="row">
                    <div class="col-md-1">
                        <div class="form-group label-floating">
                            <label class="control-label">ID</label>
                            <input typeof="text" class="form-control" asp-for="@Model.TenantId" readonly>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="optionsCheckboxes" asp-for="Disabled">
                                    Disabled
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Company name</label>
                            <input type="text" class="form-control" asp-for="TenantName">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Alias</label>
                            <input type="text" class="form-control" asp-for="TenantAlias">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Access Key</label>
                            <input type="text" class="form-control" asp-for="AccessKey">
                        </div>
                    </div>
                   
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Domain Name</label>
                            <input type="text" class="form-control" asp-for="TenantDomain">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group label-floating">
                            <label class="control-label">Database Name</label>
                            <input type="text" class="form-control" asp-for="TenantDatabase">
                        </div>
                    </div>
                </div>
               
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Notes</label>
                            <div class="form-group label-floating">
                                <label class="control-label"> Enter additional information here...</label>
                                <textarea class="form-control" rows="5" asp-for="Notes"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                @*<button  class="btn btn-primary pull-right" onclick="demo.showNotification('bottom','center')">Notification</button>*@
                <a asp-cocntroller="OrganizationSettings" asp-action="Display" asp-route-id="@Model.TenantId" class="btn btn-primary pull-right">Cancel</a>
                <button type="submit" class="btn btn-primary pull-right">Update</button>
                <div class="clearfix"></div>

            </form>
        </div>
    </div>

    

</div>
@*<script src="~/js/material/bootstrap-notify.js"></script>
<script src="~/js/site.js"></script>*@

Management/UI/Old/TaskSchedulerManager.Web/Views/OrganizationSettings/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

Management/UI/Old/TaskSchedulerManager.Web/Views/OrganizationSettings/List.cshtml
@model IEnumerable<TaskSchedulerManager.Web.Models.OrganizationSettingsViewModels.CreateOrganizationSettingsViewModel>

@{
    ViewData["Title"] = "List";
}


<div class="col-lg-12 col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="blue">
            <h4 class="title">All Organizations</h4>
            <p class="category"></p>
        </div>
        <div class="card-content table-responsive">
            <table class="table table-hover">
                <thead class="text-warning">
                <th>ID</th>
                <th>Name</th>
                <th>Domain</th>
                <th>Database</th>
                <th>Actions</th>
                </thead>
                <tbody>
                    @foreach (var org in Model)
                    {
                        <tr>
                            <td>@org.TenantId</td>
                            <td>@org.TenantName</td>
                            <td>@org.TenantDomain</td>
                            <td>@org.TenantDatabase</td>
                            <td class="td-actions">
                                <a rel="tooltip" title="Edit" class="btn btn-success btn-simple btn-xs" asp-controller="OrganizationSettings" asp-action="Edit" asp-route-id="@org.TenantId">
                                    <i class="material-icons">edit</i>
                                </a>
                                <a rel="tooltip" title="View" class="btn btn-info btn-simple btn-xs" asp-controller="OrganizationSettings" asp-action="Display" asp-route-id="@org.TenantId">
                                    <i class="material-icons">launch</i>
                                </a>

                                <a rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs" asp-controller="OrganizationSettings" asp-action="Delete" asp-route-id="@org.TenantId">
                                    <i class="material-icons">close</i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Management/UI/Old/TaskSchedulerManager.Web/Views/OrganizationSettings/New.cshtml
@model TaskSchedulerManager.Web.Models.OrganizationSettingsViewModels.CreateOrganizationSettingsViewModel
@{
    ViewData["Title"] = "New";
}





<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="blue">
            <h4 class="title">Organization</h4>
            <p class="category">Add details for the new organization</p>
        </div>
        <div class="card-content">
            <form asp-controller="OrganizationSettings" asp-action="New" method="post">
                <div class="row" style="visibility:hidden;">
                    <div class="col-md-1">
                        <div class="form-group label-floating">
                            <label class="control-label">ID</label>
                            <input type="hidden" typeof="text" class="form-control" asp-for="@Model.TenantId" readonly>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group label-floating">

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="optionsCheckboxes" asp-for="Disabled">
                                    Disabled
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Company name</label>
                            <input type="text" class="form-control" asp-for="TenantName">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Alias</label>
                            <input type="text" class="form-control" asp-for="TenantAlias">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Access Key</label>
                            <input type="text" class="form-control" asp-for="AccessKey">
                        </div>
                    </div>
                   
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group label-floating">
                            <label class="control-label">Domain Name</label>
                            <input type="text" class="form-control" asp-for="TenantDomain">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group label-floating">
                            <label class="control-label">Database Name</label>
                            <input type="text" class="form-control" asp-for="TenantDatabase">
                        </div>
                    </div>
                </div>
               
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Notes</label>
                            <div class="form-group label-floating">
                                <label class="control-label"> Enter additional information here...</label>
                                <textarea class="form-control" rows="5" asp-for="Notes"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <a asp-controller="Home" asp-action="Index" class="btn btn-primary pull-right">Cancel</a>
                <button type="submit" class="btn btn-primary pull-right">Create</button>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>